// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcvvzalvyvvjimzctwti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjdnZ6YWx2eXZ2amltemN0d3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NzU3NzcsImV4cCI6MjA3NTE1MTc3N30._sV-D92KF4Kp043QJHp5P-IFuEzviVXDZ8fyc3_FxEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});